# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soclist',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
