# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20170926_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='soclist',
        ),
    ]
