<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
>>>>>>> 26ea2e7b37ada947e854bed8410820022a930e73
