# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_auto_20170926_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='anouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('soc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.soclist')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='soc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.anouncements'),
        ),
    ]
