<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_home',
            name='en_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile_home',
            name='ph_no',
            field=models.BigIntegerField(),
        ),
    ]
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_home',
            name='en_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile_home',
            name='ph_no',
            field=models.BigIntegerField(),
        ),
    ]
>>>>>>> 26ea2e7b37ada947e854bed8410820022a930e73
